config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'notifications/index'

  root "top#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :poems, only: [:index, :show]

end

app/models/blog.rb
class Blog < ActiveRecord::Base
    validates :title, presence: true
    validates :content, presence: true

    belongs_to :user
    has_many :comments, dependent: :destroy
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_blog, only:[:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def show
    @comment = @blog.comments.build
    @comments = @blog.comments
    Notification.find(params[:notification_id]).update(read: true) if params[:notification_id]
    @notifications_count = Notification.where(user_id: current_user.id).where(read: false).count
  end

  def new
    if params[:back]
      @blog = Blog.new(blogs_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blogs_params)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blogs_path, notice: "ブログを作成しました！"
      NoticeMailer.sendmail_blog(@blog).deliver
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @blog.update(blogs_params)
      redirect_to blogs_path, notice: "ブログを更新しました！"
    else
      render "edit"
    end
  end

  def confirm
    @blog = Blog.new(blogs_params)
    render :new if @blog.invalid?
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "ブログを削除しました！"
  end

  private
  def blogs_params
    params.require(:blog).permit(:title, :content)
  end

  #idをキーとして値を取得
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
        if action_name == "new" || action_name == "confirm"
            confirm_blogs_path
        elsif action_name == "edit"
            blog_path
        end
    end
end

app/views/blogs/_form.html.erb
<%= form_for(@blog, url: choose_new_or_edit) do |f| %>
    <% if @blog.errors.any? %>
        <div id="error_explanation">
            <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
            <ul>
                <% @blog.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.label :タイトル %>
    <%= f.text_field :title, class: "form-control" %>
    <br>
    <%= f.label :内容 %>
    <%= f.text_field :content, class: "form-control" %>
    <br>
    <%= f.submit "投稿", class: "btn btn-primary btn-block" %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<div class="container">
    <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">

        <h3>以下の内容で、送信する。</h3>
        
        <%= form_for(@blog) do |f| %>
            <%= f.hidden_field :title %>
            <%= f.hidden_field :content %>
            
            <p>タイトル:<%= @blog.title %></p>
            <p>本文:<%= @blog.content %></p>
            <%= f.submit "登録", class: "btn btn-primary btn-block" %>
        <% end %>
        
        <%= form_for(@blog, url: new_blog_path, method: "get") do |f| %>
            <%= f.hidden_field :title %>
            <%= f.hidden_field :content %>
            <%= f.submit "もどる", name: "back", class: "btn btn-default btn-block" %>
        <% end %>
    </div>
</div>

app/views/blogs/edit.html.erb
<div class="container">
    <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h2>ブログを編集する</h2>
        <%= render "form" %>
    </div>
</div>

app/views/blogs/index.html.erb
<div class="container">
    <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
        <p><%= notice %></p>

        <h1>ブログ一覧</h1>
        <%= link_to "ブログを作成する", new_blog_path, class: "btn btn-default" %>

        <% @blogs.each do |blog| %>
            <div class="row">
              <%= link_to blog_path(blog) do %>
                <h4><strong>タイトル:<%= blog.title %></strong></h4>
              <% end %>
              <%= profile_img(blog.user, size: :small) if profile_img(blog.user) %>
              <p>作成者:<%= blog.user.name %></p>
              <p>本文:<%= blog.content %></p>
              <%= link_to "編集", edit_blog_path(blog.id), class: "btn btn-default btn-sm btn-success" %>
              <%= link_to "削除", blog_path(blog.id), method: :delete, data: {confirm: "本当に削除していいですか？"}, class: "btn btn-default btn-sm btn btn-danger" %>
            </div>
        <% end %>
        <br>
    </div>
</div>

<section>
    <div id="page-top-btn" class="page-top-btn">
        <p><a class="move-page-top" id="move-page-top">▲</a></p>
    </div>
</section>

app/views/blogs/new.html.erb
<div class="container">
    <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
        <h2>ブログを作成する</h2>
        <%= render "form" %>
    </div>
</div>

app/views/blogs/show.html.erb
<div class="child row">
  <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <div class="blog-text">
      <p class="left"><strong>タイトル</strong></p>
      <p class="left"><%= @blog.title %></p>
      <p class="left"><strong>内容</strong></p>
      <p class="left"><%= @blog.content %></p>
      <p class="right">
        <strong>作成時間</strong>
        <%= @blog.created_at.strftime("%y/%m/%d %p %l:%M") %>
      </p>
    </div>
    <p>コメント一覧</p>
    <p id="notice" class="text-muted h3"><%= notice %></p>
    <div id="comments_area">
      <%= render partial: 'comments/index', locals: { comments: @comments, blog: @blog } %>
    </div>
    <%= render partial: 'comments/form', locals: { comment: @comment, blog: @blog } %>
    <% if current_user.id == @blog.user_id %>
      <br>
      <%= link_to 'ブログを編集する', edit_blog_path(@blog), class: "btn btn-default btn-block"  %>
    <% end %>
    <br>
    <%= link_to '戻る', blogs_path, class: "btn btn-default btn-block"  %>
  </div>
</div>

<section>
    <div id="page-top-btn" class="page-top-btn">
        <p><a class="move-page-top" id="move-page-top">▲</a></p>
    </div>
</section>