config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'notifications/index'

  root "top#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :poems, only: [:index, :show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :blog
  has_many :notifications, dependent: :destroy

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only:[:edit, :update, :destroy]
  before_action :set_blog, only:[:edit, :update]

  def create
    @comment = current_user.comments.build(comment_params)
    @blog = @comment.blog
    unless @blog.user_id == @comment.user_id
      @notification = @comment.notifications.build(user_id: @blog.user.id)
    end

    respond_to do |format|
      if @comment.save
        flash.now[:notice] = "コメントを投稿しました。"
        format.html{redirect_to blog_path(@blog)}
        format.js {render :index}

        unless @comment.blog.user_id == current_user.id
          Pusher.trigger("user_#{@comment.blog.user_id}_channel", "comment_created", {
          message: "あなたの作成したブログにコメントがつきました"
          })
        end
        Pusher.trigger("user_#{@comment.blog.user_id}_channel", 'notification_created', { unread_counts: Notification.where(user_id: @comment.blog.user.id, read: false).count })
      else
        format.html {render :new}
      end
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to blog_path(@blog), notice: "コメントを更新しました。"
    else
      render "edit"
    end
  end

  def destroy
    @comment.destroy
    flash.now[:notice] = "コメントを削除しました。"
    respond_to do |format|
      format.js {render :index}
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:blog_id, :content)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
  def set_blog
    @blog = Comment.find(params[:id]).blog
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@blog, @comment], remote: true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= @comment.errors.count %>件のエラーがあります。</h2>

      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :blog_id %>
  <div class="field">
    <%= f.text_field :content, placeholder: "内容", class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "登録する", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% unless comment.id.nil? %>
    <li>
      <p class="left"><%= profile_img(comment.user, size: :xsmall)%>&nbsp;&nbsp;<%= comment.user.name %>さんがコメントしました。</p>
      <p class="left"><%= comment.content %></p>
      <% if current_user.id == comment.user.id %>
        <p class="right">
          <%= link_to '', edit_blog_comment_path(blog, comment), class: "fa fa-pencil-square-o fa-lg" %>
          <%= link_to '', blog_comment_path(blog, comment), class: "fa fa-trash-o fa-lg", method: :delete, remote: true, data: { confirm: "本当に削除していいですか？" } %>
        </p>
      <% end %>
    </li>
    <% end %>
  <% end %>
</ul>

app/views/comments/edit.html.erb
<div class="container">
    <div class="wrapper col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
      <h2>コメントを編集する</h2>
      <%= form_for([@blog, @comment]) do |f| %>
        <% if @comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= @comment.errors.count %>件のエラーがあります。</h2>

            <ul>
              <% @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.hidden_field :blog_id %>
        <div class="field">
          <%= f.text_field :content, placeholder: "内容", class: "form-control" %>
        </div>
        <br>
        <div class="actions">
          <%= f.submit "登録する", class: "btn btn-primary btn-block" %>
        </div>
      <% end %>
      <%= link_to '戻る', blog_path(@blog) %>
    </div>
</div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.blog.comments, blog: @comment.blog }) %>")
$(':text').val('')
$("p#notice").html("<%= j(flash[:notice]) %>")