config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'notifications/index'

  root "top#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :poems, only: [:index, :show]

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable

  mount_uploader :avatar, AvatarUploader

  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_relationships, foreign_key: "followed_id", class_name: "Relationship", dependent: :destroy

  has_many :followed_users, through: :relationships, source: :followed
  has_many :followers, through: :reverse_relationships, source: :follower

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.find_by(email: auth.info.email)

    unless user
      user = User.new(
        name: auth.extra.raw_info.name,
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        image_url: auth.info.image,
        password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save(validate:false)
    end
    user
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.find_by(provider: auth.provider, uid: auth.uid)

    unless user
      user = User.new(
        name: auth.info.nickname,
        image_url: auth.info.image,
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email ||= "#{auth.uid}-#{auth.provider}@example.com",
        password: Devise.friendly_token[0, 20]
      )
      user.skip_confirmation!
      user.save
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def update_with_password(params, *options)
    if provider.blank?
      super
    else
      params.delete :current_password
      update_without_password(params, *options)
    end
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  def twitter
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash=nil)
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only:[:show]

  def index
    @users = User.all
  end

  def show
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users/omniauth_callbacks_helper.rb
module Users::OmniauthCallbacksHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_form.html.erb
<div id="follow_form_<%= user.id %>">
  <% if user == current_user %>
    <p class="text-danger h4">あなた</p>
  <% elsif !current_user.following?(user) %>
    <%= form_for(current_user.relationships.build(followed_id: user.id), remote: true) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%=f.submit "フォロー", class: "btn btn-large btn-primary margin-top10" %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.find_by(followed_id: user.id), html: { method: :delete }, remote: true) do |f| %>
      <%= f.submit "つながりを解除", class: "btn btn-large margin-top10" %>
    <% end %>
  <% end %>
</div>

app/views/users/_followed_users.html.erb
<div class="clearfix">
  <h3><%= @user.name %> がフォローしているユーザー</h3>
  <% users = @user.followed_users %>
  <% if users.empty? %>
    <p class="text-muted">現在フォローしているユーザはいません</p><br>
  <% else %>
    <% users.each do |user| %>
      <div class="container-child col-md-3 col-sm-4 col-xs-6 img-margin">
        <%= profile_img(user, size: :small) %><br>
        <%= user.name %><br>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_followers.html.erb
<div class="clearfix">
  <h3><%= @user.name %> のフォロワー</h3>
  <% users = @user.followers %>
  <% if users.empty? %>
    <p class="text-muted">現在フォロワーはいません</p><br>
  <% else %>
    <% users.each do |user| %>
      <div class="container-child col-md-3 col-sm-4 col-xs-6 img-margin">
        <%= profile_img(user, size: :small) %><br>
        <%= user.name %><br>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_person.html.erb
<div class="container-child col-md-3 col-sm-4 col-xs-6 img-margin">
  <%= profile_img(user, size: :small) %><br>
  <%= user.name %><br>
  <%= user.email %><br>
  <%= link_to "ユーザ詳細", user_path(user), class: "btn btn-default margin-top10" %>
  <%= render "follow_form", user:user %>
  <% unless user.id == current_user.id %>
    <div class="item margin-top10">
      <%= link_to "メッセージ", conversations_path(sender_id: current_user.id, recipient_id: user.id), method: "post" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="container">
  <h2>ユーザ一覧</h2>
  <% @users.each do |user| %>
    <% next if user.id == current_user.id %>
    <%= render "person", user:user %>
  <%end%>
  <% myself = @users.find(current_user.id) %>
  <%= render "person", user:myself %>
</div>

app/views/users/show.html.erb
<div class="container">
  <h2>ユーザ詳細</h2>
    <br>
    <%= profile_img(@user, size: :small) %><br>
    <%= @user.name %><br>
    <%= @user.email %><br>
    <%= link_to "ユーザ一覧に戻る", users_path, class: "btn btn-default margin-top10" %><br>
    <hr>
    <%= render "followed_users", user:@user %><br>
    <hr>
    <%= render "followers", user:@user %><br>
</div>