config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :relationships, only: [:create, :destroy]

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :conversations do
    resources :messages
  end

  get 'notifications/index'

  root "top#index"

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :poems, only: [:index, :show]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Achieve</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>

    <% if user_signed_in? %>
    <script>
      var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>',{
        cluster: 'ap1',
        encrypted: true
      });

      var channel = pusher.subscribe("user_<%= current_user.id %>_channel");
      channel.bind('comment_created', function(data) {
        alert(data.message);
      });
      channel.bind('notification_created', function(data) {
      $('#unread_count').html(data.unread_counts);
      });

    </script>
    <% end %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Achieve", root_path, class: "navbar-brand" %>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to "お問い合わせ", new_contact_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "ブログ", blogs_path %></li>
                  <li><%= link_to "ユーザ一覧", users_path if user_signed_in? %></li>
                  <li><%= link_to "メッセージ", conversations_path if user_signed_in? %></li>
                </ul>
              </li>
              <% if user_signed_in? %>
                <li><%= link_to "マイページ", edit_user_registration_path %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to "ログイン", new_user_session_path %></li>
                <li><%= link_to "サインアップ", new_user_registration_path %></li>
              <% end %>

              <% if user_signed_in? %>
                <li>
                  <%= link_to notifications_index_path, class: "navbar-brand" do %>
                    <i class="fa fa-bell fa-1x"><span id="unread_count"><%= @notifications_count %></span></i>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <%= yield %>

    <footer>
        <p>運営会社DIVE INTO CODE株式会社</p>
        <p>©️2015-2017 Copyright DIVE INTO CODE Corp.</p>
    </footer>
  </body>
</html>